### ISSUE TITLE
2017 Version

### ISSUE THREAD

**Issue by Teknel** [frederiksen/Stateless-Designer#2]
Are you working on VS2017 update of this excellent extension?

**Comment by frederiksen** [comment]
Hi @Teknel 
No - not right now. However I don't think it is that big a task upgrading this extension. Either someone can help - and provide a PR with the changes or I will do it when I get time for this task.

**Comment by frederiksen** [comment]
Did the migration. Please try it out @Teknel

**Comment by Teknel** [comment]
I was able to do it successfully.

Make some modifications to be able to select the sending node against cases that have multiple return transitions.

I will finish packing and send it to you.

 

The only problem detected with Visual Studio 2017 is an error with the right click on the xml editor that produces a VS shutdown.

 

Thanks.

 


-------------------------------------------
José María Cuchian
Teknel Research

Beruti 4441 5to Of"45"
Te: +54 (11) 4772-4230 
Buenos Aires (C1425BDA) - ARGENTINA

 

De: Morten Frederiksen [mailto:notifications@github.com] 
Enviado el: Saturday, March 18, 2017 12:43 PM
Para: frederiksen/Stateless-Designer <Stateless-Designer@noreply.github.com>
CC: Teknel <jmcuchian@teknel.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [frederiksen/Stateless-Designer] 2017 Version (#2)

 

Did the migration. Please try it out @Teknel <https://github.com/Teknel>

**Comment by Teknel** [comment]
Hello Morten.

 

This is the StatelessDesigner version with the modifications for VS2017.

There is also a VS2017T version that was added in the TryFireTrigger function:

 

Public Trigger SenderTrigger;

Public State SenderState;

Public State TargetState;

 

These variables store the Trigger that generated the transaction and the State from where it is generated.

 

From the external class that hosts the StatelesMachine can be used to determine the Guard conditions.

 

this.sm.Guard_Login_To_InputUser_Trig_UserInvalidated = new SM.GuardClauseDelegate (delegate () {return sm.TargetState == SM.State.InputUser;});

 

If (sm.SenderState == SM.State.Start || sm.SenderState == SM.State.InputPassword)

{

this.IsRegistered = false;

…

Sm.TargetState = SM.State.InputUser;

}

 

Any questions, please let me know.

 

Thank you for your excellent work.

 


-------------------------------------------
José María Cuchian
Teknel Research

Beruti 4441 5to Of"45"
Te: +54 (11) 4772-4230 
Buenos Aires (C1425BDA) - ARGENTINA

 

De: Morten Frederiksen [mailto:notifications@github.com] 
Enviado el: Saturday, March 18, 2017 12:43 PM
Para: frederiksen/Stateless-Designer <Stateless-Designer@noreply.github.com>
CC: Teknel <jmcuchian@teknel.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [frederiksen/Stateless-Designer] 2017 Version (#2)

 

Did the migration. Please try it out @Teknel <https://github.com/Teknel>

**Comment by frederiksen** [comment]
Please create a PR - https://help.github.com/articles/creating-a-pull-request/
Then I will review your suggested changes
