### ISSUE TITLE
Source code license

### ISSUE THREAD

**Issue by maximgolunov** [frederiksen/Stateless-Designer#6]
Would it be possible to specify the license type for this project? Our org would like to contribute but needs license terms first.

**Comment by frederiksen** [comment]
Sure. I'm absolutely not an expert in license type. I need to find one - any suggestion from you?

**Comment by maximgolunov** [comment]
If you don't have special opinion - I'd suggest to go with [MIT license](https://opensource.org/licenses/mit-license.php). It is the simplest and most permissive possible. You can read more [here](https://www.quora.com/What-are-the-important-differences-between-the-most-common-open-source-licenses).

**Comment by frederiksen** [comment]
Done. I haven't done much on this project lately - so it's great if you can help with some new ideas:-)
